<a href="https://colab.research.google.com/github/Jasper-Sergio-Jasperyuu/58013-Linear_Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [28]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
D = np.array([[1, 2], [3, 4]])

#a.)
a1 = np.dot(A, B)
print("a:\n", a1)

#b.)
b1 = D + D
b2 = np.add(D, D)
print("b:\n", b1)
print("or:\n", b2)

#c.)
c1 = np.multiply(2, C)
print("c: \n", c1)

a:
 [[22 28]
 [49 64]]
b:
 [[2 4]
 [6 8]]
or:
 [[2 4]
 [6 8]]
c: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2

In [27]:
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])
#i, j, k
#cross = jk - kj, ki - ik, ij - ji
cross = [(A[1]*B[2])-(A[2]*B[1]), (A[2]*B[0])-(A[0]*B[2]), (A[0]*B[1])-(A[1]*B[0])]
#print("Problem 2:\n", np.cross(A, B)) # for verification
cross

Problem 2:
 [20 -4 -3]
