<a href="https://colab.research.google.com/github/Jasper-Sergio-Jasperyuu/58013-Linear_Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [25]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
D = np.array([[1, 2], [3, 4]])

#a.)
a1 = np.dot(A, B)
print("a:\n", a1)

#b.)
b1 = D + D
b2 = np.add(D, D)
print("b:\n", b1)
print("or:\n", b2)

#c.)
c1 = np.multiply(C, C)
print("c: \n", c1)

a:
 [[22 28]
 [49 64]]
b:
 [[2 4]
 [6 8]]
or:
 [[2 4]
 [6 8]]
c: 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


Problem 2

In [27]:
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

print("Problem 2:\n", np.cross(A, B))

Problem 2:
 [20 -4 -3]
