<a href="https://colab.research.google.com/github/Jasper-Sergio-Jasperyuu/58013-Linear_Algebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [1]:
import numpy as np
A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
B = np.array([[A], [A*10]]) # Shows that A is multiplied by 10
print("NUMBERS AND ITS MULTIPLICATION BY 10: \n", B.reshape(2,10))

NUMBERS AND ITS MULTIPLICATION BY 10: 
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [2]:
import numpy as np
A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
B = A.reshape(10, 1)
C = np.multiply(A, B)
C

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

Question 2

In [ ]:
import numpy as np
A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
B = np.array([[A], [A*10]])
C = np.array([[B[0]], [B[0]*2], [B[1]], [B[1]*2]])
C.reshape(4, 10)
print("NUMBERS AND ITS MULTIPLICATION BY 2: \n", C[0], '\n', C[1])
print("Multiples of 10 and its doubles: \n", C[2], '\n', C[3])

NUMBERS AND ITS MULTIPLICATION BY 2: 
 [[[[ 1  2  3  4  5  6  7  8  9 10]]]] 
 [[[[ 2  4  6  8 10 12 14 16 18 20]]]]
Multiples of 10 and its doubles: 
 [[[[ 10  20  30  40  50  60  70  80  90 100]]]] 
 [[[[ 20  40  60  80 100 120 140 160 180 200]]]]


In [4]:
import numpy as np
A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
B = A.reshape(10, 1)
C = np.multiply(A, B)
C
print(C*2)

[[  2   4   6   8  10  12  14  16  18  20]
 [  4   8  12  16  20  24  28  32  36  40]
 [  6  12  18  24  30  36  42  48  54  60]
 [  8  16  24  32  40  48  56  64  72  80]
 [ 10  20  30  40  50  60  70  80  90 100]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 16  32  48  64  80  96 112 128 144 160]
 [ 18  36  54  72  90 108 126 144 162 180]
 [ 20  40  60  80 100 120 140 160 180 200]]


Question 3

In [ ]:
Q3 = np.eye(4,4)
Q3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Question 4

In [ ]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("Size of matrix: ", np.size(matrix))
print("Shape of matrix:", np.shape(matrix))
print("Dimensions of matrix:", np.ndim(matrix))

Size of matrix:  12
Shape of matrix: (3, 4)
Dimensions of matrix: 2


Question 5

In [ ]:
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

array3 = np.add(arrayOne, arrayTwo)
print("Sum:\n",array3)
print("Sum as squared: \n", array3**2)


Sum:
 [[20 39 33]
 [25 25 28]]
Sum as squared: 
 [[ 400 1521 1089]
 [ 625  625  784]]
