<a href="https://colab.research.google.com/github/Jasper-Sergio-Jasperyuu/58013-Linear_Algebra/blob/main/Python_Exercise_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Coding Activity 4

In [23]:
import numpy as np

A = np.array([[-0.4],
              [4.3],
              [-0.6]])
B = np.array([-0.2, 0.2, 1])
C = np.array([-0.2, 2.1, -1.5])
print('A=\n', A,
      '\nB=\n', B,
      '\nC=\n', C)

add = np.add(A+B, C)
minus = np.subtract(A-B, C)
multiply = np.multiply(A*B, C)
divide = np.divide(A/B, C)

print(f"Addition of Array = \n{add}\n",
      f"Subraction of Array = \n{minus}\n",
      f"Multiplication of Array = \n{multiply}\n",
      f"Division of Array = \n{np.around(divide, 3)}") # rounds each element of the matrix to 3 decimal places

A=
 [[-0.4]
 [ 4.3]
 [-0.6]] 
B=
 [-0.2  0.2  1. ] 
C=
 [-0.2  2.1 -1.5]
Addition of Array = 
[[-0.8  1.9 -0.9]
 [ 3.9  6.6  3.8]
 [-1.   1.7 -1.1]]
 Subraction of Array = 
[[ 0.  -2.7  0.1]
 [ 4.7  2.   4.8]
 [-0.2 -2.9 -0.1]]
 Multiplication of Array = 
[[-0.016 -0.168  0.6  ]
 [ 0.172  1.806 -6.45 ]
 [-0.024 -0.252  0.9  ]]
 Division of Array = 
[[-10.     -0.952   0.267]
 [107.5    10.238  -2.867]
 [-15.     -1.429   0.4  ]]
