<a href="https://colab.research.google.com/github/Jasper-Sergio-Jasperyuu/58013-Linear_Algebra/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Addition

In [13]:
import numpy as np
A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

print(A+B+C)

print(np.add(A,np.add(B,C)))

np.sum(B)


[ 4  3 -1]
[ 4  3 -1]


2

Vector Subtraction

In [12]:
print(np.subtract(A,B))

A-B


[-2  1  2]


array([-2,  1,  2])

Vector Multiplication

In [14]:
print(np.multiply(A,B))

A*B


[3 2 0]


array([3, 2, 0])

Vector Division

In [15]:
np.divide(A,B)

print(A/B)

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
print(C//D)

np.array(A/B,dtype=int)


[ 0.33333333  2.         -0.        ]
[3. 1. 7.]


array([0, 2, 0])