<a href="https://colab.research.google.com/github/Jasper-Sergio-Jasperyuu/58013-Linear_Algebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


Coding activity 10


In [ ]:
#x is flour, y is yeast, z is eggs
# 30x +10y +120z = 12500
# 40x + 20y + 200z = 18000
# 50x + 40y + 360z = 25700

A = np.array([[30,10,120],[40,20,200],[50,40,360]])
A1 = np.array([[12500, 10, 120],[18000, 20, 200], [25700, 40, 360]])
A2 = np.array([[30,12500,120],[40,18000,200],[50,25700,360]])
A3 = np.array([[30,10,12500],[40,20,18000],[50,40,25700]])

a = round(np.linalg.det(A))
a1 = round(np.linalg.det(A1))
a2 = round(np.linalg.det(A2))
a3 = round(np.linalg.det(A3))

x = np.divide(a1,a)
y = np.divide(a2,a)
z = np.divide(a3,a)
print(round(x))
print(round(y))
print(round(z))

330
140
10
