<a href="https://colab.research.google.com/github/Jasper-Sergio-Jasperyuu/58013-Linear_Algebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
A = np.array([
    [1,4],
    [0,3]
])
round(np.linalg.det(A))

3

In [ ]:
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
round(np.linalg.det(B))

-235

Activity

In [15]:
#Associative Property
print('Associative Property= (AB)C = A(BC)')
A = np.array([[1,2,3],[1,2,3],[1,2,3]])
B = np.array([[4,5,6],[4,5,6],[4,5,6]])
C = np.array([[7,8,9],[7,8,9],[7,8,9]])
print("A =",A,"\nB =", B,"\nC =", C)
AB = np.dot(A,B)
BC = np.dot(B,C)
print("(AB)C = ", np.dot(AB,C))
print("A(BC) = ", np.dot(A,BC))
print(np.equal(np.dot(AB,C), np.dot(A,BC)))

Associative Property= (AB)C = A(BC)
A = [[1 2 3]
 [1 2 3]
 [1 2 3]] 
B = [[4 5 6]
 [4 5 6]
 [4 5 6]] 
C = [[7 8 9]
 [7 8 9]
 [7 8 9]]
(AB)C =  [[630 720 810]
 [630 720 810]
 [630 720 810]]
A(BC) =  [[630 720 810]
 [630 720 810]
 [630 720 810]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
#Distributive Property
print('Distributive= A(B+C) = AB + AC')
A = np.array([[1,2,3],[1,2,3],[1,2,3]])
B = np.array([[4,5,6],[4,5,6],[4,5,6]])
C = np.array([[7,8,9],[7,8,9],[7,8,9]])
print("A =",A,"\nB =", B,"\nC =", C)
print("A(B+C)=", np.dot(A, np.add(B,C)))
print('AB + AC=', np.add(np.dot(A,B),np.dot(A,C)))
print(np.equal(np.dot(A, np.add(B,C)), np.add(np.dot(A,B),np.dot(A,C))))

Distributive= A(B+C) = AB + AC
A = [[1 2 3]
 [1 2 3]
 [1 2 3]] 
B = [[4 5 6]
 [4 5 6]
 [4 5 6]] 
C = [[7 8 9]
 [7 8 9]
 [7 8 9]]
A(B+C)= [[66 78 90]
 [66 78 90]
 [66 78 90]]
AB + AC= [[66 78 90]
 [66 78 90]
 [66 78 90]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#Closure Property or Scaling
print('If array is multiplied to a constant c, the product shall be the elements*c')
A = np.array([[1,2,3],[1,2,3],[1,2,3]])
print('Array= ', A)
print('A*3=',A*3)


If array is multiplied to a constant c, the product shall be the elements*c
Array=  [[1 2 3]
 [1 2 3]
 [1 2 3]]
A*3= [[3 6 9]
 [3 6 9]
 [3 6 9]]


In [17]:
#Identity Property
print('Any matrix multiplied to identity matrix remains the same')
A = np.array([[1,2,3],[1,2,3],[1,2,3]])
print("A = \n", A)
print("A*Identity = \n", np.dot(A, np.eye(3,3)))
print(np.equal(np.dot(A, np.add(B,C)), np.add(np.dot(A,B),np.dot(A,C))))

Any matrix multiplied to identity matrix remains the same
A = 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
A*Identity = 
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
#Zero Property
print('Any matrix multiplied by a zero matrix is equal to zero')
A = np.array([[1,2,3],[1,2,3],[1,2,3]])
print("A = \n", A)
print("A*zero = \n", np.dot(A, np.zeros([3,3])), '\nor\n', A*0)

Any matrix multiplied by a zero matrix is equal to zero
A = 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
A*zero = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
or
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [18]:
#Commutative Property
print("AB != BA")
A = np.array([[1,2,3],[4,5,3],[1,7,2]])
print("A=\n",A)
B = np.array([[4,5,6],[6,4,-1],[3,5,2]])
print("B=\n",B)
print('AB=\n', np.dot(A,B))
print('BA=\n', np.dot(B,A))
print(np.equal( np.dot(B,A), np.dot(A,B) ))

AB != BA
A=
 [[1 2 3]
 [4 5 3]
 [1 7 2]]
B=
 [[ 4  5  6]
 [ 6  4 -1]
 [ 3  5  2]]
AB=
 [[25 28 10]
 [55 55 25]
 [52 43  3]]
BA=
 [[30 75 39]
 [21 25 28]
 [25 45 28]]
[[False False False]
 [False False False]
 [False False False]]
