<a href="https://colab.research.google.com/github/Jasper-Sergio-Jasperyuu/58013-Linear_Algebra/blob/main/Vector%2C_Spaces%2C_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector

In [1]:
import numpy as np
A = np.array([4, 3])
B = np.array([2, -5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


Shape of the matrix

In [27]:
#Checking Shapes
#Shapes tells us how many rows and columns are there
ball1 = np.array([[1], [2], [3]])
print(f"Column Vector: {ball1}")
ball1 = np.array([1, 2, 3])
print(ball1)
ball2 = np.array([0, 1, -1])
print(ball2)
b1 = np.shape(ball1) + np.shape(ball2)
print(b1)
x = np.ndim(ball1)
y = np.ndim(ball2)
print(x)
print(y)

Column: [[1]
 [2]
 [3]]
[1 2 3]
[ 0  1 -1]
(3, 3)
1
1


Spaces

In [44]:
#Addition
A = np.array([4, 3])
B = np.array([2,-5])
R = np.add(A, B)
print(R)

[ 6 -2]


In [38]:
#Subtraction

R1 = np.subtract(A, B)
print(R1)

[2 8]


In [39]:
#Scalar Product
S = np.array([2])
V = A*S
print(V)

[8 6]


In [71]:
#Multiply
B = B.reshape(2, 1)
c1 = np.multiply(A, B)
print(np.multiply(A, B))

[[  8   6]
 [-20 -15]]


In [72]:
#Property of Matrix
#Identity Matrix
c = np.eye(2, 2) #np.eye(dimension)
print(c)
#Zero Matrix
d = np.zeros([4,4]) #np.zeros([dimension])
print(d)
#Full Matrix
e = np.full((3, 3), 7)
print(e)
#Transpose of Matrix
print(np.transpose(c1))

[[1. 0.]
 [0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[  8 -20]
 [  6 -15]]
